import Head from "next/head"

const Login = () => {
    return (
        <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link
      rel="stylesheet"
      href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"
    />
      </Head>
        <div className="container-fluid">
            <div className="row h-screen">
                <div className="d-none d-md-block col-md-6 bg-secondary login-bg-img">Hello login dark</div>
                <div className="col-sm-12 col-md-6 bg-white m-auto">
                    <div className="container px-0 px-md-5">
                        <div className="brand-logo mb-4 text-primary">
                            <h1>Traffikr.IO</h1>
                        </div>
                        <div className="mb-4">
                            <h3>Welcome back!</h3>
                            <small className="text-secondary">Please enter your email and password to continue from where you stopped</small>
                        </div>
                     <form>
                        <div className="mb-3">
                            <label htmlFor="emailAddress" className="form-label">Email address</label>
                            <input type="email" className="form-control form-control-lg" id="emailAddress" name="emailAddress" placeholder="eg. name@example.com" />
                        </div>
                        <div className="mb-3">
                            <label htmlFor="password" className="form-label">Password</label>
                            <input type="password" className="form-control form-control-lg" id="password" name="password" placeholder="password" />
                        </div>
                    <div className="d-flex justify-content-between align-items-center mb-3">
                        <div className="form-check">
                            <input className="form-check-input" type="checkbox" value="" id="keepMeSignedIn" />
                            <label className="form-check-label" for="keepMeSignedIn">
                                Keep me signed in
                            </label>
                        </div>
                        <div className="forgot-password">
                            <a href="#" class="link-primary">Forgot Password?</a>
                        </div>
                                               
                    </div>
                        <div className="pt-3">
                            <input type="submit" className="btn btn-primary btn-block btn-lg" value="Login" id="Login" />
                        </div>
                    </form>
                    <div className="d-grid gap-2 d-md-flex justify-content-md-center mt-5">
                        <button className="btn btn-lg btn-fb btn-block" type="button"><i className="lab la-facebook-f"></i>&nbsp;Facebook</button>
                        <button className="btn btn-lg btn-gg btn-block" type="button"><i className="lab la-google-plus"></i>&nbsp;Google</button>
                    </div>
                    <div className="d-grid gap-2 d-md-flex justify-content-md-center mt-5">
                        <p><span className="text-secondary">Don't have and account?</span> <a href="/register" class="link-primary">Create</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</>)
}

export default Login
