import Head from "next/head"

const Register = () => {
    return (
        <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link
      rel="stylesheet"
      href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"
    />
      </Head>
        <div className="container-fluid">
            <div className="row h-screen">
                <div className="d-none d-md-block col-md-6 bg-secondary register-bg-img"></div>
                <div className="col-sm-12 col-md-6 bg-white m-auto">
                    <div className="container px-0 px-md-5">
                        <div className="brand-logo mb-4 text-primary">
                            <h1>Traffikr.IO</h1>
                        </div>
                        <div className="mb-4">
                            <h3>Welcome!</h3>
                            <small className="text-secondary">Please register with required credentials to get started</small>
                        </div>
                     <form>
                        <div className="mb-3">
                            <label htmlFor="fullName" className="form-label">Full Name</label>
                            <input type="text" className="form-control form-control-lg" name="fullName" id="fullName" placeholder="eg. John Doe" />
                        </div>
                        <div className="mb-3">
                            <label htmlFor="emailAddress" className="form-label">Email address</label>
                            <input type="email" className="form-control form-control-lg" id="emailAddress" name="emailAddress" placeholder="name@example.com" />
                        </div>
                        <div className="mb-3">
                            <label htmlFor="password" className="form-label">Password</label>
                            <input type="password" className="form-control form-control-lg" id="password" placeholder="password" />
                        </div>
                        <div className="mb-3 form-check">
                            <input className="form-check-input" type="checkbox" value="" id="termsAgreed" name="termsAgreed" />
                            <label className="form-check-label" for="termsAgreed">
                                I agree to all terms and condition
                            </label>
                        </div>
                        <div className="pt-3">
                            <input type="submit" className="btn btn-primary btn-block btn-lg" value="Register" id="register" />
                        </div>
                    </form>
                
                    <div className="mt-3">
                        <p><span className="text-secondary">Already have and account?</span> <a href="/login" class="link-primary">Login</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</>)
}

export default Register
